### ISSUE TITLE
Can't clone en-us\about_Tesla.help.txt

### ISSUE THREAD

**Issue by jthelin** [JonnMsft/TeslaPSModule#1]
There is something strange going on in this repo because en-us\about_Tesla.help.txt 
appears as a file with embedded backslash but on Windows that can't be cloned.

Did you intend for en-us to be a directory with file about_Tesla.help.txt within that?

**Comment by JonnMsft** [comment]
Thank you Jorgen. As you note, I did intend en-us to be a directory.

My more important concern is that the REST APIs used to work, but now consistently return error

Invoke-RestMethod : We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

Are you also seeing this?

**Comment by JonnMsft** [comment]
I have good news. With some assistance, I am converting TeslaPSModule over to the new OAUTH-based API. I hope to have an update posted in a few days.

**Comment by JonnMsft** [comment]
It's fixed! Please try the new version, and have a look at the [Wiki](https://github.com/JonnMsft/TeslaPSModule/wiki).
