### ISSUE TITLE
Old API endpoint

### ISSUE THREAD

**Issue by bryanvine** [JonnMsft/TeslaPSModule#13]
Invoke-RestMethod : {"response":null,"error":"Endpoint deprecated: Please update your App.","error_description":""}
At C:\users\bryan\repo\TeslaPSModule\Tesla.psm1:162 char:10

**Comment by JonnMsft** [comment]
Thanks Bryan. I haven't been maintaining this and I'm not surprised that the endpoint has been retired. You're welcome to have a run at updating the project if you like.

**Comment by JonnMsft** [comment]
closed
