### ISSUE TITLE
ID Issue

### ISSUE THREAD

**Issue by rochoje** [JonnMsft/TeslaPSModule#4]
When I try to "Connect-Tesla"

I enter my credentials and receive

Where-Object : The input name "id" cannot be resolved to a property. At C:\Program Files\WindowsPowerShell\Modules\Tesla\1.0.2\Tesla.psm1:227 char:35 + $vehicle = $vehicle | Where-Object id -eq $vehicleId + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidArgument: (@{response=System.Object[]; count=1}:PSObject) [Where-Object], PSArgum entException + FullyQualifiedErrorId : PropertyNotFound,Microsoft.PowerShell.Commands.WhereObjectCommand

**Comment by JonnMsft** [comment]
I apologize for the delay. It looks like I am using syntax which only works on newer versions of PowerShell. Probably I should fix this. What version are you running? You might consider upgrading.

**Comment by eponerine** [comment]
Hey @JonnMsft , I am experiencing this problem on **Windows 10 1809** - PSVersion **5.1.17134.407**

I'll take a look at the failing line and see if the API changed.

**Comment by eponerine** [comment]
I'm still fairly new to the Tesla API, but I think I see the issue. Unsure what the JSON payload looked like 2 years ago, but this is what it looks like now when you do Connect-Tesla:

```
{
    "response": [
        {
            "id": XXXXXXX,
            "vehicle_id": YYYYYYY,
            "vin": "ZZZZZZZZZ",
            "display_name": "ErnieTesla.",
            "option_codes": "AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0",
            "color": null,
            "tokens": [
                "tokenABCD",
                "tokenEFGH"
            ],
            "state": "asleep",
            "in_service": false,
            "id_s": "6666666666666",
            "calendar_enabled": true,
            "api_version": 6,
            "backseat_token": null,
            "backseat_token_updated_at": null
        }
    ],
    "count": 1
} 
```

And the failing line in your PoSH (227) doesn't expand out the JSON object first. It looks like this:

```
$vehicle = $vehicle | ? id -eq $vehicleId
```

When it should look like this:

```
$vehicle = $vehicle.response | ? id -eq $vehicleId
```

I didn't check the other aspects of the module (Get-Tesla, Set-Tesla) to see if there are similar issues. Will work with a locally edited copy of the module and submit a pull request in a few days.

**Comment by eponerine** [comment]
Actually, scratch all of that. Just update line 223 to:

```
$vehicle = Invoke-RestMethod -Uri "$apiUri/vehicles" -Method Get -UserAgent $user_agent -Headers $headers | Select Response
```

**Comment by JonnMsft** [comment]
Thanks Ernie! I'll be watching for your PR. While you're in there, could you fix the PSv3 compat problem discussed in the last thread?

Once this is in, I will update PowerShell Gallery.

Thanks! Jon

**Comment by phuongpham** [comment]
I'm using the powershell script from Azure and not facing this issue (yet)

**Comment by eponerine** [comment]
> While you're in there, could you fix the PSv3 compat problem discussed in the last thread?

I don't see any other threads detailing this (unless I'm losing my mind). The only PS v3 issue I have found so far is **Invoke-RestMethod** complaining about **-ContentType** being a required parameter (as opposed to it being passed in the headers). Does that sound familiar?

**Comment by scautomation** [comment]
has the pull request been put in? I got a tesla last month and tried the powershell module and was getting similar issues when trying to connect.

**Comment by eponerine** [comment]
Hoping to do it tonight; it's literally 2 line changes.

**Comment by scautomation** [comment]
that would be awesome. I want to take the data and put it in log analytics.

**Comment by eponerine** [comment]
Hey @JonnMsft , I'm unsure if you have the repo settings configured to allow external contributions, but I'm receiving this message from GitHub Desktop when trying to Publish:

> Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

**Comment by JonnMsft** [comment]
I just invited you as a collaborator. Please try now.

**Comment by eponerine** [comment]
PR submitted. Please review and accept and merge and let's roll!
